spring:
    application:
        name: haengunse-server

    config:
        import: application-dev.yml

server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true